# Usamos una imagen base de Node.js
FROM node:18

# Establecemos el directorio de trabajo dentro del contenedor
WORKDIR /usr/src/app

# Copiamos los archivos de la aplicación (package.json y package-lock.json)
COPY package*.json ./

# Instalamos las dependencias del proyecto
RUN npm install

# Copiamos el resto de la aplicación (código fuente, controladores, rutas, etc.)
COPY . .

# Exponemos el puerto en el que el microservicio se ejecutará
EXPOSE 3004

# Comando para ejecutar el microservicio
CMD ["npm", "run", "dev"]
